name: "Dispatch Docs"

description: "Dispatch docs to main repo"

inputs:
  base:
    description: "location for base documentation"
    required: true
    default: "docs"
  token:
    description: "token to trigger workflow elsewhere"
    required: true
  cf_token:
    description: "Cloudflare API token"
    required: true

runs:
  using: "node12"
  main: "dist/main.js"
