on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  dispatch_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: aws configure set aws_access_key_id ${{ secrets.AWS_KEY }}
      - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET }}
      - run: zip docs.zip docs -r
      - run: aws s3 sync docs.zip s3://svelte-docs/svelte-test-docs@next.zip
      # - name: publish
      #   id: projects
      #   uses: ./.github/actions/dispatch
      #   with:
      #     token: ${{ secrets.WORKFLOW_TOKEN }}
      #     aws_key_id: ${{ secrets.AWS_KEY }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET }}
