on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  dispatch_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        id: projects
        uses: ./.github/actions/dispatch
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          cf_token: ${{ secrets.KV_WRITE_TOKEN }}
