on:
  push:
    branches:
      - main
jobs:
  dispatch_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        id: projects
        uses: ./.github/actions/dispatch